# Defaults tasks for role httpd-feeds
- name: Importing specific distro variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"

- name: Ensuring some pkgs are installed
  yum:
    name: "{{ feeds_pkgs }}"
    state: installed

- name: Ensuring we have a document root for vhost
  file:
    path: "{{ feeds_httpd_dir }}"
    state: directory
  tags:
    - feeds

- name: Generating .repo file that will be used to fetch content and generate .xml
  template:
    src: repo-rss.repo.j2
    dest: /etc/yum.repos.d/repo-rss.repo
  tags:
    - feeds

- name: Generating leeching script
  template:
    src: rss-generator.j2
    dest: /usr/libexec/centos/rss-generator
    mode: 0755
  tags:
    - feeds

- name: Download rss.py tool 
  get_url:
    url: https://git.resf.org/sig_core/toolkit/raw/branch/devel/mangle/generators/rss.py
    dest: /usr/libexec/centos/repo-rss.py
    mode: '0755'

- name: Cron job for rss-generator
  cron:
    name: rss-generator 
    minute: "*/20"
    job: /usr/libexec/centos/rss-generator

- name: Configuring httpd
  import_role:
    name: httpd
  vars:
    httpd_tls: "{{ feeds_httpd_tls }}"
    httpd_html_autoindex_title: "CentOS Feeds"
    httpd_html_autoindex_content: "{{ feeds_httpd_header }}"

- name: Configuring httpd vhost
  template:
    src: 20_feeds_vhost.conf.j2
    dest: /etc/httpd/conf.d/20_feeds_vhost.conf
    mode: 0644
  notify:
    - restart_httpd

- name: Configuring https
  template:
    src: "{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
    mode: 0644
  notify:
    - restart_httpd
  with_items:
    - ssl-feeds-vhost.conf
  when: feeds_httpd_tls  
   
- import_role:
    name: httpd
    tasks_from: pki-tls
  vars:
    pki_hostname: "{{ feeds_httpd_hostname }}"
  notify:
    - restart_httpd
  tags:
    - tls
  when: feeds_httpd_tls
